server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  datasource:
    url:
    username:
    password:

  redis:
    host:
    port: 6379

security:
  jwt:
    token:
      bearer-type: Bearer
      secret-key:
      access-token-expire-time:
      refresh-token-expire-time:

springdoc:
  packages-to-scan: yapp.buddycon
  swagger-ui:
    path: /buddycon/swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true

